### ISSUE TITLE
Quarto and webexercises

### ISSUE THREAD

**Issue by bwelman** [PsyTeachR/webexercises#12]
To use webexercises with quarto you need to add the css and js files to the format html option in the _quarto.yml file. For example

```
format:
  html:
    css: include/webex.css
    include-after-body: include/webex.js
```

Unfortunately Quarto doesn't support a `before_chapter_script`. One way to solve this is to use a setup code chunk at the start of each file. {See discussion](https://github.com/quarto-dev/quarto-cli/issues/997)

`{r, file = "R/webex.R", include = FALSE}`

Maybe it is possible to create a add-to-quarto function.
